version: '3'
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=haraka
      - POSTGRES_USER=haraka
      - POSTGRES_DB=haraka
    ports:
      - '5432:5432'
    volumes:
      - '.docker/db:/var/lib/postgresql/data'
